//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SportsStore.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Podaj ulicê")]
        [Display(Name = "Ulica")]
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Podaj kod pocztowy")]
        [Display(Name = "Kod pocztowy")]
		[RegularExpression(@"^\(?([0-9]{2})\)?[-. ]?([0-9]{3})$", ErrorMessage = "Podaj kod pocztowy w formacie 00-000")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Podaj numer domu/mieszkania")]
        [Display(Name = "Numer domu /mieszkania")]
        [StringLength(10,ErrorMessage = "Maksymalnie 10 znaków")]
        public string Number { get; set; }

        [Required(ErrorMessage = "Wybierz miasto")]
        [Display(Name = "Miasto")]
        public Nullable<int> CityId { get; set; }

        public String FullName => $"{Code} {City.Name} {Street} {Number}";
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
