//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SportsStore.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Podaj nazwe produktu")]
        [Display(Name = "Nazwa produktu")]
        [StringLength(30, ErrorMessage = "Maksymalnie 30 znaków")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Podaj cene")]
        [Display(Name = "Cena")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Podaj dodatni¹ cene")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Podaj opis")]
        [Display(Name = "Opis")]
        [StringLength(200, ErrorMessage = "Maksymalnie 200 znaków")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Wybierz kategorie")]
        [Display(Name = "Kategoria")]
        public Nullable<int> CategoryId { get; set; }

        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
